runtime: python39
entrypoint: gunicorn -w 4 -k uvicorn.workers.UvicornWorker src.main:app

instance_class: F2

env_variables:
  PORT: "8080"

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10

handlers:
- url: /.*
  script: auto
  secure: always