version: '3.8'

services:
  rom-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rom-analysis-api
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    environment:
      - ENVIRONMENT=production
      - LOG_LEVEL=info
      - MAX_WORKERS=4
      - TIMEOUT=120
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"

  # Optional Nginx for production deployment
  nginx:
    image: nginx:alpine
    container_name: rom-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./static:/var/www/static
    depends_on:
      - rom-api
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

# Create a Docker volume for persistent data
volumes:
  data:
    driver: local